import { Weapon, WeaponId } from './types';

export const WEAPONS: Record<WeaponId, Weapon> = {
  daggers: {
    id: 'daggers',
    name: 'Парные Клинки Тени',
    description: 'Маленький радиус, молниеносная скорость атаки и частый урон.',
    type: 'arc',
    baseRange: 90,
    baseDamage: 26,
    baseCooldown: 0.22,
    spreadAngle: Math.PI * 0.75, // 135 degrees
    knockback: 18,
    price: 0,
    color: '#38bdf8',
    trailColor: 'rgba(56, 189, 248, 0.4)',
  },
  sword: {
    id: 'sword',
    name: 'Меч Паладина',
    description: 'Сбалансированное оружие со средним радиусом и широким дуговым взмахом.',
    type: 'arc',
    baseRange: 135,
    baseDamage: 52,
    baseCooldown: 0.45,
    spreadAngle: Math.PI * 0.85, // 150 degrees
    knockback: 35,
    price: 150,
    color: '#fbbf24',
    trailColor: 'rgba(251, 191, 36, 0.45)',
  },
  spear: {
    id: 'spear',
    name: 'Копьё Грифона',
    description: 'Большой радиус колющего выпада. Пронзает толпу врагов насквозь в узком секторе.',
    type: 'thrust',
    baseRange: 230,
    baseDamage: 78,
    baseCooldown: 0.62,
    spreadAngle: Math.PI * 0.35, // 63 degrees
    knockback: 45,
    price: 250,
    color: '#a855f7',
    trailColor: 'rgba(168, 85, 247, 0.5)',
  },
  bow: {
    id: 'bow',
    name: 'Эльфийский Лук Ветра',
    description: 'Огромный радиус атаки. Выпускает быстрые пронзающие стрелы на дальнюю дистанцию.',
    type: 'projectile',
    baseRange: 380,
    baseDamage: 58,
    baseCooldown: 0.48,
    projectileSpeed: 620,
    knockback: 25,
    price: 200,
    color: '#4ade80',
    trailColor: 'rgba(74, 222, 128, 0.4)',
  },
  staff: {
    id: 'staff',
    name: 'Посох Архимага',
    description: 'Дальнобойные магические сферы, взрывающиеся при контакте с нанесением зонального урона.',
    type: 'aoe_burst',
    baseRange: 330,
    baseDamage: 85,
    baseCooldown: 0.75,
    projectileSpeed: 440,
    aoeRadius: 75,
    knockback: 50,
    price: 320,
    color: '#f43f5e',
    trailColor: 'rgba(244, 63, 94, 0.45)',
  },
  hammer: {
    id: 'hammer',
    name: 'Молот Титана',
    description: 'Круговой AoE удар на 360°. Сокрушает землю, наносит огромный урон и отбрасывает всех вокруг.',
    type: 'circle',
    baseRange: 170,
    baseDamage: 135,
    baseCooldown: 1.05,
    knockback: 85,
    price: 380,
    color: '#f97316',
    trailColor: 'rgba(249, 115, 22, 0.5)',
  },
};
